### ISSUE TITLE
Version 0.3.7 introduces breaking changes

### ISSUE THREAD

**Issue by abdulmth** [paritytech/orchestra#80]
The following project doesn't compile anymore when using the newest version 0.3.7 of orchestra.

```toml
[package]
name = "tempProj"
version = "0.1.0"
edition = "2021"

[dependencies]
cumulus-client-consensus-aura = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-crates-io-v1.7.0" }
```

with the following error 
```
   --> /.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/e046d3b/polkadot/node/overseer/src/lib.rs:460:1
    |
460 | / #[orchestra(
461 | |     gen=AllMessages,
462 | |     event=Event,
463 | |     signal=OverseerSignal,
464 | |     error=SubsystemError,
465 | |     message_capacity=2048,
466 | | )]
    | |__^ use of undeclared type `PriorityLevel`
    |
    = note: this error originates in the attribute macro `orchestra` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these items
    |
64  + use crate::gen::PriorityLevel;
    |
64  + use orchestra::PriorityLevel;
    |

error[E0412]: cannot find type `NormalPriority` in this scope
   --> /.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/e046d3b/polkadot/node/overseer/src/lib.rs:460:1
    |
460 | / #[orchestra(
461 | |     gen=AllMessages,
462 | |     event=Event,
463 | |     signal=OverseerSignal,
464 | |     error=SubsystemError,
465 | |     message_capacity=2048,
466 | | )]
    | |__^ not found in this scope
    |
    = note: this error originates in the attribute macro `orchestra` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these items
    |
64  + use crate::gen::NormalPriority;
    |
64  + use orchestra::NormalPriority;
```

Pinning the indirect orchestra dependency to the version 0.3.6 fixes the issue (Make sure the version is reflected in the cargo.lock file)
```toml
[package]
name = "tempProj"
version = "0.1.0"
edition = "2021"

[dependencies]
cumulus-client-consensus-aura = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-crates-io-v1.7.0" }

[patch.crates-io]
orchestra = { git = "https://github.com/paritytech/orchestra.git", tag = "v0.3.6" }
```
I might be wrong but probably the latest release is the issue here.
